{% set name = "phasepy" %}
{% set version = "0.0.50" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/phasepy-{{ version }}.tar.gz
  sha256: 947d52678dcc4021595b2e2b76c35da0b3695aad30f003c2ce81882975534664

build:
  number: 2
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - cython
  run:
    - numpy
    - pandas
    - python
    - scipy

test:
  imports:
    - phasepy
    - phasepy.actmodels
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/gustavochm/phasepy
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Multiphase multicomponent Equilibria
  description: |
    Phasepy is an open-source scientific Python package for calculation
    of physical properties of phases at thermodynamic equilibrium. Main
    application areas include computation of fluid phase equilibria and
    interfacial properties.
  doc_url: https://github.com/gustavochm/phasepy
  dev_url: https://github.com/gustavochm/phasepy

extra:
  recipe-maintainers:
    - jan-janssen
