{% set name = "phasepy" %}
{% set version = "0.0.56" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/gustavochm/phasepy/archive/v{{ version }}.tar.gz
  sha256: 9cccc48fc480acebe6315b52aaaa8a2456888456374acc509914e5e3954cbdd0

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - pip
    - python
    - setuptools
    - cython
    - numpy
  run:
    - numpy
    - pandas
    - python
    - scipy
    - openpyxl

test:
  imports:
    - phasepy
    - phasepy.actmodels
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/gustavochm/phasepy
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Multiphase multicomponent Equilibria
  description: |
    Phasepy is an open-source scientific Python package for calculation
    of physical properties of phases at thermodynamic equilibrium. Main
    application areas include computation of fluid phase equilibria and
    interfacial properties.
  doc_url: https://github.com/gustavochm/phasepy
  dev_url: https://github.com/gustavochm/phasepy

extra:
  recipe-maintainers:
    - jan-janssen
