{% set name = "phasepy" %}
{% set version = "0.0.53" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/phasepy-{{ version }}.tar.gz
  sha256: 048d04d3e003e3f978caa0ac66d080b86ceb36f8ef23e146bdc1d13cb47ba2a8
  patches: scipy.patch

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - pip
    - python
    - setuptools
    - cython
  run:
    - numpy
    - pandas
    - python
    - scipy
    - openpyxl

test:
  imports:
    - phasepy
    - phasepy.actmodels
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/gustavochm/phasepy
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Multiphase multicomponent Equilibria
  description: |
    Phasepy is an open-source scientific Python package for calculation
    of physical properties of phases at thermodynamic equilibrium. Main
    application areas include computation of fluid phase equilibria and
    interfacial properties.
  doc_url: https://github.com/gustavochm/phasepy
  dev_url: https://github.com/gustavochm/phasepy

extra:
  recipe-maintainers:
    - jan-janssen
